repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
  - repo: https://github.com/awebdeveloper/pre-commit-tslint/
    rev: v0.0.2
    hooks:
      - id: tslint
        additional_dependencies: ['tslint@5.0.0', 'tslint-eslint-rules']
