export enum ErrorCode {
  MATCH_EXISTENT = 'MATCH_EXISTENT',
  MATCH_NOT_FOUND = 'MATCH_NOT_FOUND',
  MATCH_FULL = 'MATCH_FULL',

  INVALID_MATCH_DATE = 'INVALID_MATCH_DATE',

  MISSING_REQUEST_PARAM = 'MISSING_REQUEST_PARAM',
  MISSING_QUERY_PARAM = 'MISSING_QUERY_PARAM',
  INVALID_BODY = 'INVALID_BODY',

  PLAYER_EXISTENT = 'PLAYER_EXISTENT'
}
